package require    msgcat
namespace import ::msgcat::*

mcset ko ApkZipper ApkZipper


# Commons
mcset ko Sorry 죄송합니다
mcset ko Input 입력
mcset ko Delete 삭제
mcset ko Confirm 확인
mcset ko Processing {처리 중...}
mcset ko Error 에러
mcset ko Success. 성공.
mcset ko Failed. 실패.
mcset ko Yes 예
mcset ko No 아니오
mcset ko {Yes to all} {모두 예}
mcset ko {No to all} {모두 아니오}
mcset ko {} {}
mcset ko {} {}
mcset ko {} {}
mcset ko {} {}
mcset ko {} {}
mcset ko {} {}
mcset ko {} {}

# File open dialog

# Main window menu
mcset ko {&Config}			{설정(&C)}
mcset ko {&SDK Function}	{SDK(&S)}
mcset ko {&Etc Function}	{기타(&E)}
mcset ko {Zip level} 		{압축세기}
mcset ko {Ziplevel 0}		{0 (압축 안 함)}
mcset ko {Ziplevel 1}		1
mcset ko {Ziplevel 2}		2
mcset ko {Ziplevel 3}		3
mcset ko {Ziplevel 4}		4
mcset ko {Ziplevel 5}		5
mcset ko {Ziplevel 6}		6
mcset ko {Ziplevel 7}		7
mcset ko {Ziplevel 8}		8
mcset ko {Ziplevel 9}		{9 (최고 압축)}
mcset ko {Decompile target}	{디컴파일 대상}
mcset ko {Sources}			{소스만}
mcset ko {Resources}		{리소스만}
mcset ko {Both}      		{둘 다}
mcset ko {The others}		{나머지만}
mcset ko {ADB Shell}		{ADB Shell}
mcset ko {Take phone log}	{폰 로그 가져오기}
mcset ko {ADB Connect}   	{ADB 원격접속}
mcset ko {Reboot}        	{리부팅}
mcset ko {Enter recovery}	{복구모드로 진입}
mcset ko {Enter download}	{다운로드모드로 진입}
mcset ko {Check update}		{업데이트 확인}
mcset ko {Visit website}	{홈페이지}
mcset ko {Help}				{도움말}

mcset ko {Clean folder}		{폴더 정리}
mcset ko {Delete current result} {현재 결과물 삭제}
mcset ko {Delete current workdir} {현재 작업폴더 삭제}
mcset ko {Delete current except original} {현재 원본만 빼고 삭제}
mcset ko {Delete current all} {현재 선택한 것 전부 삭제}
mcset ko {Delete all result} {모든 결과물 삭제}
mcset ko {Delete all workdir} {모든 작업폴더 삭제}
mcset ko {Delete all except original} {모두 원본만 빼고 삭제}
mcset ko {Delete all} {모두 삭제}

# Main window button
mcset ko {Import from phone} {폰에서 가져오기}
mcset ko {Select app} {앱 선택하기}
mcset ko {Extract} {압축풀기}
mcset ko {Decompile} {디컴파일}
mcset ko {Explore project} {작업폴더 열기}
mcset ko {Optimize png} {PNG 최적화}
mcset ko {Recompress ogg} {OGG 재압축}
mcset ko {Zip} {압축}
mcset ko {Compile} {컴파일}
mcset ko {Sign} {사인}
mcset ko {Install} {설치하기}
mcset ko {Export to phone} {폰으로 내보내기}

# Other dialogs
mcset ko {Extension mismatch} {확장자 불일치}
mcset ko "Do you want to import this?\n%s" "확장자가 .apk가 아닙니다.\n정말 다음 파일을 추가할까요?\n%s"
mcset ko {Not yet ready} {아직 준비되지 않았습니다}
mcset ko {Cannot access to %s} {%s에 접근할 수 없습니다}
mcset ko {Please wait} {기다려주세요}
mcset ko {Already op exist} {다른 작업이 진행 중 입니다}
