package require    msgcat
namespace import ::msgcat::*

# English text is built-in.

mcset {} {Ziplevel 0}		{0 (Low)}
mcset {} {Ziplevel 1}		1
mcset {} {Ziplevel 2}		2
mcset {} {Ziplevel 3}		3
mcset {} {Ziplevel 4}		4
mcset {} {Ziplevel 5}		5
mcset {} {Ziplevel 6}		6
mcset {} {Ziplevel 7}		7
mcset {} {Ziplevel 8}		8
mcset {} {Ziplevel 9}		{9 (High)}

mcset {} {ADB pull} {Import from phone}
mcset {} {ADB push} {Export to phone}