package require    msgcat
namespace import ::msgcat::*

mcset {} APKZIPPER "Apkzipper"

# File open dialog
mcset ko ALL_FILE "모든 파일"
mcset ko ALL_READABLE_FILE "열 수 있는 파일"
mcset ko APK_FILE "apk 파일"
mcset ko JAR_FILE "jar 파일"
mcset ko OPEN_MULTIPLE_FILES_DIALOG_TITLE "Ctrl, Shift키로 여러 개를 열 수 있습니다."

# Main window menu
mcset ko CONFIG "설정"
mcset ko ZIP_LEVEL "압축세기"
mcset ko ZLEVEL0 "0(약함)"
mcset ko ZLEVEL1 "1"
mcset ko ZLEVEL2 "2"
mcset ko ZLEVEL3 "3"
mcset ko ZLEVEL4 "4"
mcset ko ZLEVEL5 "5"
mcset ko ZLEVEL6 "6"
mcset ko ZLEVEL7 "7"
mcset ko ZLEVEL8 "8"
mcset ko ZLEVEL9 "9(강함)"
mcset ko DECOMPILE_OPTION "디컴파일 대상"
mcset ko SOURCES "소스만"
mcset ko RESOURCES "리소스만"
mcset ko BOTH "소스와 리소스"
mcset ko THE_OTHERS "나머지만"

mcset ko SDK_FUNCTION "SDK 기능"
mcset ko ADB_SHELL "ADB 쉘"
mcset ko TAKE_PHONE_LOG "휴대폰 로그 가져오기"
mcset ko ADB_CONNECT "ADB 쉘 무선연결"
mcset ko REBOOT "리부팅"
mcset ko ENTER_RECOVERY "복구모드 진입"
mcset ko FLASH_RECOVERY "복구이미지 쓰기"
mcset ko ENTER_DOWNLOAD "다운로드모드 진입"

mcset ko ETC_FUNCTION "기타기능"
mcset ko CHECK_UPDATE "업데이트 확인"
mcset ko CLEAN_FOLDER "폴더 정리"
mcset ko DELETE_CURRENT_RESULT "현재 결과물 삭제"
mcset ko DELETE_CURRENT_WORKDIR "현재 작업폴더 삭제"
mcset ko DELETE_CURRENT_EXCEPT_ORIGINAL "원본만 빼고 삭제"
mcset ko DELETE_CURRENT_ALL "현재 선택한 것 전부 삭제"
mcset ko DELETE_ALL_RESULT "모든 결과물 삭제"
mcset ko DELETE_ALL_WORKDIR "모든 작업폴더 삭제"
mcset ko DELETE_ALL_EXCEPT_ORIGINAL "원본만 빼고 모두 삭제"
mcset ko DELETE_ALL "모두 삭제"
mcset ko VISIT_WEBSITE "웹사이트"
mcset ko HELP 도움말


# Main window button
mcset ko IMPORT_FROM_PHONE "폰에서 가져오기"
mcset ko SELECT_APP "파일 선택"
mcset ko EXTRACT "압축풀기"
mcset ko DECOMPILE'N'INSTALL_FRAMEWORK "디컴파일 &\n필요한 apk 설치(우클릭)"
mcset ko OPEN_FOLDER "작업폴더 열기"
mcset ko OPTIMIZE_PNG "png 최적화"
mcset ko RECOMPRESS_OGG "ogg 재압축"
mcset ko ZIP "압축"
mcset ko COMPILE "컴파일"
mcset ko SIGN "사인"
mcset ko INSTALL "설치"
mcset ko PUSH_TO_PHONE "폰으로 전송하기"


# Other dialogs
mcset ko SELECT_FRAMEWORK_FILE_OR_FOLDER "Select framework file or folder"


