package require    msgcat
namespace import ::msgcat::*

mcset {} APKZIPPER "Apkzipper"

# File open dialog
mcset {} ALL_FILE "All files"
mcset {} ALL_READABLE_FILE "All readable files"
mcset {} APK_FILE "apk file"
mcset {} JAR_FILE "jar file"
mcset {} OPEN_MULTIPLE_FILES_DIALOG_TITLE "Multiple selection allowed by Ctrl, Shift."


# Main window menu
mcset {} CONFIG "Config"
mcset {} ZIP_LEVEL "Zip level"
mcset {} ZLEVEL0 "0(Low)"
mcset {} ZLEVEL1 "1"
mcset {} ZLEVEL2 "2"
mcset {} ZLEVEL3 "3"
mcset {} ZLEVEL4 "4"
mcset {} ZLEVEL5 "5"
mcset {} ZLEVEL6 "6"
mcset {} ZLEVEL7 "7"
mcset {} ZLEVEL8 "8"
mcset {} ZLEVEL9 "9(High)"
mcset {} DECOMPILE_OPTION "Decompile option"
mcset {} SOURCES "Sources"
mcset {} RESOURCES "Resources"
mcset {} BOTH "Both"
mcset {} THE_OTHERS "The others"

mcset {} SDK_FUNCTION "SDK function"
mcset {} ADB_SHELL "ADB shell"
mcset {} TAKE_PHONE_LOG "Take phone log"
mcset {} ADB_CONNECT "ADB connect"
mcset {} REBOOT "Reboot"
mcset {} ENTER_RECOVERY "Enter recovery mode"
mcset {} FLASH_RECOVERY "Flash recovery image"
mcset {} ENTER_DOWNLOAD "Enter download mode"

mcset {} ETC_FUNCTION "Etc function"
mcset {} CHECK_UPDATE "Check for update"
mcset {} CLEAN_FOLDER "Clean folders"
mcset {} DELETE_CURRENT_RESULT "Delete current output"
mcset {} DELETE_CURRENT_WORKDIR "Delete current project"
mcset {} DELETE_CURRENT_EXCEPT_ORIGINAL "Delete current except original"
mcset {} DELETE_CURRENT_ALL "Delete current all"
mcset {} DELETE_ALL_RESULT "Delete all output"
mcset {} DELETE_ALL_WORKDIR "Delete all project"
mcset {} DELETE_ALL_EXCEPT_ORIGINAL "Delete all except original"
mcset {} DELETE_ALL "Delete all"
mcset {} VISIT_WEBSITE "Visit website"
mcset {} HELP Help


# Main window button
mcset {} IMPORT_FROM_PHONE "Import from phone"
mcset {} SELECT_APP "Select app"
mcset {} EXTRACT "Extract"
mcset {} DECOMPILE'N'INSTALL_FRAMEWORK "Decompile &\nInstall framework(right click)"
mcset {} OPEN_FOLDER "Open folder"
mcset {} OPTIMIZE_PNG "Optimize png"
mcset {} RECOMPRESS_OGG "Recompress ogg"
mcset {} ZIP "Zip"
mcset {} COMPILE "Compile"
mcset {} SIGN "Sign"
mcset {} INSTALL "Install"
mcset {} PUSH_TO_PHONE "Push to phone"


# Other dialogs
mcset {} SELECT_FRAMEWORK_FILE_OR_FOLDER "Select framework file or folder"


