./ApkzDbg.tcl

./ApkzGUI.tcl
mcset {} {ApkZipper v1.9 alpha} {}
mcset {} {ADB Shell} {}
mcset {} {Take phone log} {}
mcset {} FLASH_RECOVERY {}
mcset {} Sorry {}
mcset {} {Not yet ready} {}
mcset {} {Clean folder} {}
mcset {} {Right click: %s} {}
mcset {} {Extension mismatch} {}
mcset {} "Do you want import this?\n%s" {}
mcset {} Yes {}
mcset {} No {}
mcset {} {Yes to all} {}
mcset {} {No to all} {}
mcset {} {Cannot access to %s} {}
mcset {} {Please wait} {}
mcset {} {Please wait} {}
mcset {} {Already op exist} {}

./ApkzMain.tcl

./ApkzSub.tcl
mcset {} {All readable file} {}
mcset {} {Apk file} {}
mcset {} {Jar file} {}
mcset {} {All file} {}
mcset {} OPEN_MULTIPLE_FILES_DIALOG_TITLE {}
mcset {} Confirm {}
mcset {} Abort {}
mcset {} {Retry with conserving data} {}
mcset {} {Retry with removing data} {}
mcset {} Abort {}
mcset {} {Retry with conserving data} {}
mcset {} {Retry with removing data} {}
mcset {} {Waiting for device...} {}
mcset {} {Type path of android file} {}
mcset {} {Cannot find java.} {}
mcset {} {Please extract/decompile app first.} {}
mcset {} {jar compiling...} {}
mcset {} {apk compiling...} {}
mcset {} {Compile failed. Task terminated.} {}
mcset {} {Adjusting compressing level...} {}
mcset {} {Please extract/decompile app first.} {}
mcset {} {Select framework file or folder} {}
mcset {} {Signing failed} {}
mcset {} Signed {}
mcset {} {Zipalign failed} {}
mcset {} Zipaligned {}
mcset {} {Type android push path} {}
mcset {} Pushing... {}
mcset {} { finished.} {}
mcset {} Processing {}
mcset {} Error {}
mcset {} {ADB logcat executed} {}
mcset {} {ADB logcat terminated} {}
mcset {} {ADB connecting... } {}
mcset {} {Connecting...} {}
mcset {} "ADB Connect" {}
mcset {} Confirm {}
mcset {} Yes {}
mcset {} No {}
mcset {} No {}
mcset {} Delete {}
mcset {} {Checking update..} {}
mcset {} {Update info not found. Please check website.} {}
mcset {} {New version found!} {}
mcset {} YES {}
mcset {} YES {}
mcset {} NO {}

./ConfigDialog.tcl
mcset {} {Tuner} {}

./pkgIndex.tcl

./Utility.tcl
mcset {} ERROR {}
mcset {} {Input} {}
mcset {} ([^ {}

